=== drashti35/XML/UNIVERSITY XML/assign2Q4.dtd
<!ELEMENT details (Student)>
		<!ELEMENT Student (Student_name,Personal_info,Result)>
		<!ELEMENT Personal_info (Address,Birthdate,Gender,Mobile_no)>
		<!ELEMENT Result (Total,Percentage,Grade)>
		<!ELEMENT Student_name (#PCDATA)>
		<!ELEMENT Address (#PCDATA)>
		<!ELEMENT Birthdate (#PCDATA)>
		<!ELEMENT Gender (Male|Female)>
		<!ELEMENT Male (#PCDATA)>
		<!ELEMENT Female (#PCDATA)>
		<!ELEMENT Mobile_no (#PCDATA)>
		<!ELEMENT Total (#PCDATA)>
		<!ELEMENT Percentage (#PCDATA)>
		<!ELEMENT Grade (Pass|First|Dist|Second|Fail)>
		<!ELEMENT Pass (#PCDATA)>
		<!ELEMENT First (#PCDATA)>
		<!ELEMENT Dist (#PCDATA)>
		<!ELEMENT Second (#PCDATA)>
		<!ELEMENT Fail (#PCDATA)>

=== drashti35/XML/UNIVERSITY XML/assign2Q4.xml
<?xml version="1.0"?>
	<!DOCTYPE details SYSTEM "assign2Q4.dtd">
	<details>
		<Student>
			<Student_name></Student_name>
			<Personal_info>
				<Address></Address>
				<Birthdate></Birthdate>
				<Gender>
					<Female></Female>
				</Gender>
				<Mobile_no></Mobile_no>
			</Personal_info>
			<Result>
				<Total></Total>
				<Percentage></Percentage>
				<Grade>
					<Pass></Pass>
				</Grade>
			</Result>
		</Student>
	</details>
	<!--Create XML document for Student where it contains the following
data:
Student Name, Personal Info (Address, Birthdate,Gender, Mobile
No, Address) ,Result(Total, Percentage, Grade)
Create External DTD declaration for Student where
• Gender has only two choices Male and Female as an element.
• Grade element should have only one of these grade element
(Pass, First, Dist., Second, Fail)-->
