=== drashti35/XML/UNIVERSITY XML/assign2Q7.dtd
<!ELEMENT details (Email)>
<!ELEMENT Email (from,to,content,course)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT content (#PCDATA|person|exercises)*>
<!ELEMENT person (#PCDATA)>
<!ELEMENT exercises (exercise)*>
<!ELEMENT exercise (topic,description)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT course (#PCDATA)>

=== drashti35/XML/UNIVERSITY XML/assign2Q7.xml
<?xml version="1.0"?>
	<!DOCTYPE details SYSTEM "assign2Q7.dtd">
	<details>
		<Email>
			<from>drashti</from>
			<to>vaibhavi</to>
			<content>bhjvv
				<person>alice</person>
				<exercises>
					<exercise>
						<topic></topic>
						<description></description>
					</exercise>
					<exercise>
						<topic></topic>
						<description></description>
					</exercise>
				</exercises>
			</content>
			<course>bcom</course>
		</Email>
	</details>
	<!--Create an XML document Email where it contains the following data :
Email (from , to ,content ( person , exercises(exercise (topic ,
description) ) , course ).
Create An External DTD for the above XML document where
• Content element of email should be mixed content.
• Exercises can have multiple exercise element.-->
