=== drashti35/XML/UNIVERSITY XML/assign2Q8.dtd
<!ELEMENT details (Student)>
<!ELEMENT Student (Roll_no,Name,Marks,Rank)>
<!ELEMENT Roll_no (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Marks (webtechnologies,XML,J2EE,NS)>
<!ELEMENT webtechnologies (#PCDATA)>
<!ELEMENT XML (#PCDATA)>
<!ELEMENT J2EE (#PCDATA)>
<!ELEMENT NS (#PCDATA)>
<!ELEMENT Rank (#PCDATA)>

=== drashti35/XML/UNIVERSITY XML/assign2Q8.xml
<?xml version="1.0"?>
	<!DOCTYPE details SYSTEM "assign2Q8.dtd">
	<details>
		<Student>
			<Roll_no>12</Roll_no>
			<Name>drashti</Name>
			<Marks>
				<webtechnologies >79</webtechnologies> 
				<XML>85</XML> 
				<J2EE>90</J2EE> 
				<NS>78</NS>
			</Marks>
			<Rank>1</Rank>
		</Student>
	</details>
	<!--Create an XML document Student where it contains the following
data :
Student (Roll_no , Name , Marks , Rank)
Create An External DTD for the above XML document where
• Marks element has web technologies , XML , J2EE ,NS as a subelement
• Marks can have only the above elements.-->
