=== drashti35/XML/UNIVERSITY XML/assign2Q6.dtd
<!ELEMENT details (Student)>
<!ELEMENT Student (Name,ID,Plan)>
<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name fname CDATA #REQUIRED>
<!ATTLIST Name lname CDATA #REQUIRED>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Plan (courses*)>
<!ELEMENT courses (course)>
<!ATTLIST courses year CDATA #REQUIRED>
<!ELEMENT course (name,shortName,record*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT shortName (#PCDATA)>
<!ELEMENT record (Grade,date)>
<!ELEMENT Grade (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== drashti35/XML/UNIVERSITY XML/assign2Q6.xml
<?xml version="1.0"?>
	<!DOCTYPE details SYSTEM "assign2Q6.dtd">
	<details>
		<Student>
			<Name fname="drashti" lname="patel">drashti</Name>
			<ID>1232</ID>
			<Plan>
				<courses year="2020">
					<course>
						<name>jakgd</name>
						<shortName>pdcn</shortName>
						<record>
							<Grade>nbxc</Grade>
							<date>12-03-2000</date>
						</record>
					</course>
				</courses>
				<courses year="2020">
					<course>
						<name>jakgd</name>
						<shortName>pdcn</shortName>
						<record>
							<Grade>nbxc</Grade>
							<date>12-03-2000</date>
						</record>
					</course>
				</courses>
			</Plan>
		</Student>
	</details>
	<!--Create an XML document Student where it contains the following data:
Student(Name (fname & Lname) , ID , Plan (courses) ). In
courses element take (year) as an attribute and (course) as an
sub-element . And Course has name , shortName , record as its
sub element. And again record has its sub element Grade , date.
Create An External DTD for the above XML document where :
• Courses element can zero or more course.
• Year attribute must appear in the element.
• Record element should appear zero or more times.-->
