=== drashti35/XML/UNIVERSITY XML/practise_exerciseQ2.dtd
<!ELEMENT Emp_details (Employee)>
			<!ELEMENT Employee (Employee_Name,Personal_info,Salary,Designation)>
			<!ELEMENT Personal_info (Address,Birthdate,Gender,Mobileno)>
			<!ELEMENT Salary (Net_salary,Gross_salary,HRA,DA)>
			<!ELEMENT Employee_Name (#PCDATA)>
			<!ELEMENT Address (#PCDATA)>
			<!ELEMENT Birthdate (#PCDATA)>
			<!ELEMENT Gender (male|female)>
			<!ELEMENT male (#PCDATA)>
			<!ELEMENT female (#PCDATA)>
			<!ELEMENT Mobileno (#PCDATA)>
			<!ELEMENT Net_salary (#PCDATA)>
			<!ELEMENT Gross_salary (#PCDATA)>
			<!ELEMENT HRA (#PCDATA)>
			<!ELEMENT DA (#PCDATA)>
			<!ELEMENT Designation (#PCDATA)>
			<!ATTLIST Designation post (HR|Manager|Technical|Consultant|Executive) #REQUIRED>

=== drashti35/XML/UNIVERSITY XML/practise_exerciseQ2.xml
<?xml version="1.0"?>
	<!DOCTYPE Emp_details SYSTEM "practise_exerciseQ2.dtd">
	<Emp_details>
		<Employee>
			<Employee_Name></Employee_Name>
			<Personal_info>
				<Address></Address>
				<Birthdate></Birthdate>
				<Gender>
					<female></female>
				</Gender>
				<Mobileno></Mobileno>
			</Personal_info>
			<Salary>
				<Net_salary></Net_salary>
				<Gross_salary></Gross_salary>
				<HRA></HRA>
				<DA></DA>
			</Salary>
			<Designation post="HR"></Designation>
		</Employee>
	</Emp_details>
<!--2. Create XML document for Employee where it contains the following data:
Employee Name, Personal Info (Address, Birthdate,Gender, Mobile
No,) ,Salary(Net salary, Gross salary, HRA, DA), Designation
Create External DTD declaration for Employee where
• Gender has only two choices Male and Female as an element.
• Designation has an attribute post and value should be Manager,Technical
Consultant, Executive, HR-->
